<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Identity\Security\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Finbuckle.MultiTenant" Version="8.1.9" />
    <PackageReference Include="Finbuckle.MultiTenant.AspNetCore" Version="8.1.9" />
    <PackageReference Include="Finbuckle.MultiTenant.EntityFrameworkCore" Version="8.1.9" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.22" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.21" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.21">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tenantix.Application\Tenantix.Application.csproj" />
    <ProjectReference Include="..\Tenantix.Domain\Tenantix.Domain.csproj" />
    <ProjectReference Include="..\Tenantix.Shared\Tenantix.Shared.csproj" />
  </ItemGroup>

</Project>
