<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Tenantix_WebApi</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.11">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.9.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Middlewares\" />
    <Folder Include="Extensions\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tenantix.Application\Tenantix.Application.csproj" />
    <ProjectReference Include="..\Tenantix.Infrastructure\Tenantix.Infrastructure.csproj" />
    <ProjectReference Include="..\Tenantix.Shared\Tenantix.Shared.csproj" />
  </ItemGroup>

</Project>
